
unused = "#79e11a"

[chiller]
  gray1 = "#464752"
  gray2 = "#565761"
  gray3 = "#b6b6b2"
  gray4 = "#ccccc7"
  black = "#282a36"
  blue = "#6272a4"
  cyan = "#8be9fd"
  green = "#50fa7b"
  magenta = "#ff79c6"
  orange = "#ffb86c"
  purple = "#bd93f9"
  red = "#ff5555"
  white = "#f8f8f2"
  yellow = "#f1fa8c"

[dark]
  button = ["chiller.black","chiller.gray3"]
  button-focus = ["chiller.black","chiller.magenta"]
  button-selected = ["chiller.white","chiller.gray3"]
  cmdline = ["chiller.black","chiller.yellow"]
  cmdline-button = ["chiller.yellow","chiller.black"]
  cmdline-border = ["chiller.black","chiller.yellow"]
  copy-mode = ["chiller.black","chiller.yellow"]
  copy-mode-alt = ["chiller.yellow","chiller.black"]
  copy-mode-label = ["chiller.white","chiller.red"]
  current-capture = ["chiller.white","themes.unused"]
  dialog = ["chiller.black","chiller.yellow"]
  dialog-button = ["chiller.yellow","chiller.black"]
  default = ["chiller.white","chiller.black"]
  filter-empty = ["chiller.black","chiller.cyan"]
  filter-intermediate = ["chiller.black","chiller.orange"]
  filter-invalid = ["chiller.black","chiller.red"]
  filter-menu = ["chiller.white","chiller.black"]
  filter-valid = ["chiller.black","chiller.green"]
  hex-byte-selected = ["chiller.white","chiller.purple"]
  hex-byte-unselected = ["chiller.white","chiller.black"]
  hex-field-selected = ["chiller.black","chiller.cyan"]
  hex-field-unselected = ["chiller.black","chiller.white"]
  hex-interval-selected = ["chiller.white","chiller.gray2"]
  hex-interval-unselected = ["chiller.white","chiller.gray1"]
  hex-layer-selected = ["chiller.white","chiller.gray2"]
  hex-layer-unselected = ["chiller.white","chiller.gray1"]
  packet-list-cell-focus = ["chiller.white","chiller.purple"]
  packet-list-cell-selected = ["chiller.white","chiller.gray2"]
  packet-list-row-focus = ["chiller.white","chiller.cyan"]
  packet-list-row-selected = ["chiller.white","chiller.gray1"]
  packet-struct-focus = ["chiller.black","chiller.cyan"]
  packet-struct-selected = ["chiller.black","chiller.gray2"]
  progress-complete = ["chiller.white","chiller.purple"]
  progress-default = ["chiller.white","chiller.black"]
  progress-spinner = ["chiller.yellow","chiller.purple"]
  spinner = ["chiller.yellow","chiller.black"]
  stream-client = ["chiller.black","chiller.red"]
  stream-match = ["chiller.black","chiller.yellow"]
  stream-search = ["chiller.black","chiller.white"]
  stream-server = ["chiller.white","chiller.blue"]
  title = ["chiller.red","unused"]

[light]
  button = ["chiller.black","chiller.white"]
  button-focus = ["chiller.black","chiller.purple"]
  button-selected = ["chiller.black","chiller.gray3"]
  cmdline = ["chiller.black","chiller.yellow"]
  cmdline-button = ["chiller.yellow","chiller.black"]
  cmdline-border = ["chiller.black","chiller.yellow"]
  copy-mode = ["chiller.white","chiller.yellow"]
  copy-mode-alt = ["chiller.yellow","chiller.white"]
  copy-mode-label = ["chiller.black","chiller.red"]
  current-capture = ["chiller.black","unused"]
  dialog = ["chiller.black","chiller.yellow"]
  dialog-button = ["chiller.yellow","chiller.black"]
  default = ["chiller.black","chiller.white"]
  filter-empty = ["chiller.black","chiller.cyan"]
  filter-intermediate = ["chiller.black","chiller.orange"]
  filter-invalid = ["chiller.black","chiller.red"]
  filter-menu = ["chiller.black","chiller.white"]
  filter-valid = ["chiller.black","chiller.green"]
  hex-byte-selected = ["chiller.white","chiller.purple"]
  hex-byte-unselected = ["chiller.black","chiller.white"]
  hex-field-selected = ["chiller.black","chiller.cyan"]
  hex-field-unselected = ["chiller.black","chiller.gray2"]
  hex-interval-selected = ["chiller.white","chiller.gray2"]
  hex-interval-unselected = ["chiller.black","chiller.gray4"]
  hex-layer-selected = ["chiller.white","chiller.gray2"]
  hex-layer-unselected = ["chiller.black","chiller.gray4"]
  packet-list-cell-focus = ["chiller.white","chiller.purple"]
  packet-list-cell-selected = ["chiller.black","chiller.gray3"]
  packet-list-row-focus = ["chiller.white","chiller.cyan"]
  packet-list-row-selected = ["chiller.black","chiller.gray4"]
  packet-struct-focus = ["chiller.black","chiller.cyan"]
  packet-struct-selected = ["chiller.black","chiller.gray4"]
  progress-complete = ["chiller.white","chiller.purple"]
  progress-default = ["chiller.white","chiller.black"]
  progress-spinner = ["chiller.yellow","chiller.black"]
  spinner = ["chiller.yellow","chiller.white"]
  stream-client = ["chiller.white","chiller.red"]
  stream-match = ["chiller.white","chiller.yellow"]
  stream-search = ["chiller.white","chiller.black"]
  stream-server = ["chiller.white","chiller.blue"]
  title = ["chiller.red","unused"]
